export type EventCard = {
  slug: string;
  category: string;
  date: string;
  time: string;
  location: string;
  price: string;
  spotsLeft: number;
  image: string;
  imagePosition?: string;
  title: string;
  text: string;
};

const yogaGroupImage =
  "https://images.pexels.com/photos/3822724/pexels-photo-3822724.jpeg?auto=compress&cs=tinysrgb&w=900";

export const events: EventCard[] = [
  {
    slug: "watercolor-painting-for-beginners",
    category: "Workshop",
    date: "17 April, Friday",
    time: "14:00 - 17:00",
    location: "Copenhagen",
    price: "295 DKK",
    spotsLeft: 8,
    image: "https://images.pexels.com/photos/11942721/pexels-photo-11942721.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 46%",
    title: "Watercolor painting for beginners",
    text: "A relaxed creative session for anyone who wants to explore color, composition, and painting in a welcoming atmosphere.",
  },
  {
    slug: "ceramic-hand-building-techniques",
    category: "Creative lab",
    date: "18 April, Saturday",
    time: "11:00 - 14:00",
    location: "Copenhagen",
    price: "345 DKK",
    spotsLeft: 3,
    image: "https://images.pexels.com/photos/5197789/pexels-photo-5197789.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 58%",
    title: "Ceramic hand building techniques",
    text: "Learn tactile hand-building methods and create your own ceramic objects through a calm, guided introduction.",
  },
  {
    slug: "sunday-yoga-19-april",
    category: "Yoga",
    date: "19 April, Sunday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Sunday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "calligraphy-and-hand-lettering",
    category: "Art session",
    date: "20 April, Monday",
    time: "18:00 - 20:30",
    location: "Copenhagen",
    price: "250 DKK",
    spotsLeft: 0,
    image: "https://images.pexels.com/photos/6925203/pexels-photo-6925203.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 52%",
    title: "Calligraphy and hand lettering",
    text: "Slow down and practice expressive lettering styles with tools, paper, and a focus on process over perfection.",
  },
  {
    slug: "knitting-circle",
    category: "Community circle",
    date: "22 April, Wednesday",
    time: "18:30 - 21:00",
    location: "Copenhagen",
    price: "180 DKK",
    spotsLeft: 12,
    image: "https://images.pexels.com/photos/5806948/pexels-photo-5806948.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 48%",
    title: "Knitting circle",
    text: "Bring your yarn, join the table, and share an evening of making, conversation, and gentle creative rhythm.",
  },
  {
    slug: "thursday-yoga-23-april",
    category: "Yoga",
    date: "23 April, Thursday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Thursday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "seasonal-ukrainian-dinner",
    category: "Dinner club",
    date: "24 April, Friday",
    time: "19:00 - 22:00",
    location: "Copenhagen",
    price: "425 DKK",
    spotsLeft: 2,
    image: "https://images.pexels.com/photos/3937667/pexels-photo-3937667.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 56%",
    title: "Seasonal Ukrainian dinner",
    text: "An intimate table gathering with comforting seasonal dishes, warm hosting, and a relaxed social atmosphere.",
  },
  {
    slug: "morning-breathwork-session",
    category: "Wellness",
    date: "26 April, Sunday",
    time: "10:00 - 11:30",
    location: "Copenhagen",
    price: "220 DKK",
    spotsLeft: 0,
    image: "https://images.pexels.com/photos/5890293/pexels-photo-5890293.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 44%",
    title: "Morning breathwork session",
    text: "A gentle guided session for grounding, quiet focus, and a softer start to the weekend.",
  },
  {
    slug: "sunday-yoga-26-april",
    category: "Yoga",
    date: "26 April, Sunday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Sunday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "thursday-yoga-30-april",
    category: "Yoga",
    date: "30 April, Thursday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Thursday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "creative-business-evening",
    category: "Talk",
    date: "30 April, Thursday",
    time: "17:30 - 19:00",
    location: "Copenhagen",
    price: "150 DKK",
    spotsLeft: 18,
    image: "https://images.pexels.com/photos/29753417/pexels-photo-29753417.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 48%",
    title: "Creative business evening",
    text: "A practical conversation for makers and hosts who want to shape ideas into clear, guest-ready formats.",
  },
  {
    slug: "sunday-yoga-3-may",
    category: "Yoga",
    date: "3 May, Sunday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Sunday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "scandinavian-floral-table-styling",
    category: "Floral styling",
    date: "4 May, Monday",
    time: "16:00 - 18:00",
    location: "Copenhagen",
    price: "310 DKK",
    spotsLeft: 6,
    image: "https://images.pexels.com/photos/35556948/pexels-photo-35556948.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 50%",
    title: "Scandinavian floral table styling",
    text: "A soft styling workshop focused on flowers, table rhythm, and details for intimate events.",
  },
  {
    slug: "thursday-yoga-7-may",
    category: "Yoga",
    date: "7 May, Thursday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Thursday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "ukrainian-brunch-and-sharing-table",
    category: "Food workshop",
    date: "8 May, Friday",
    time: "12:00 - 15:00",
    location: "Copenhagen",
    price: "390 DKK",
    spotsLeft: 4,
    image: "https://images.pexels.com/photos/20488500/pexels-photo-20488500.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 56%",
    title: "Ukrainian brunch and sharing table",
    text: "Learn to shape a warm sharing table with Ukrainian-inspired dishes and a modern Nordic feeling.",
  },
  {
    slug: "sunday-yoga-10-may",
    category: "Yoga",
    date: "10 May, Sunday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Sunday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "thursday-yoga-14-may",
    category: "Yoga",
    date: "14 May, Thursday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Thursday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "morning-movement-for-women",
    category: "Movement",
    date: "14 May, Thursday",
    time: "08:30 - 09:45",
    location: "Copenhagen",
    price: "160 DKK",
    spotsLeft: 0,
    image: "https://images.pexels.com/photos/8374552/pexels-photo-8374552.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 40%",
    title: "Morning movement for women",
    text: "A calm, low-pressure movement class for grounding, posture, and gentle strength.",
  },
  {
    slug: "sunday-yoga-17-may",
    category: "Yoga",
    date: "17 May, Sunday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Sunday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "weaving-and-textile-evening",
    category: "Craft",
    date: "20 May, Wednesday",
    time: "17:30 - 20:00",
    location: "Copenhagen",
    price: "280 DKK",
    spotsLeft: 10,
    image: "https://images.pexels.com/photos/6634212/pexels-photo-6634212.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 52%",
    title: "Weaving and textile evening",
    text: "A tactile evening with fibers, quiet conversation, and simple woven pieces to take home.",
  },
  {
    slug: "thursday-yoga-21-may",
    category: "Yoga",
    date: "21 May, Thursday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Thursday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "sunday-yoga-24-may",
    category: "Yoga",
    date: "24 May, Sunday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Sunday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "thursday-yoga-28-may",
    category: "Yoga",
    date: "28 May, Thursday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Thursday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
  {
    slug: "women-founders-coffee-circle",
    category: "Community",
    date: "28 May, Thursday",
    time: "15:00 - 17:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 15,
    image: "https://images.pexels.com/photos/33560946/pexels-photo-33560946.jpeg?auto=compress&cs=tinysrgb&w=900",
    imagePosition: "center 46%",
    title: "Women founders coffee circle",
    text: "A welcoming social circle for women building creative projects, small brands, or local formats.",
  },
  {
    slug: "sunday-yoga-31-may",
    category: "Yoga",
    date: "31 May, Sunday",
    time: "11:00 - 12:00",
    location: "Copenhagen",
    price: "120 DKK",
    spotsLeft: 12,
    image: yogaGroupImage,
    imagePosition: "center 42%",
    title: "Sunday yoga",
    text: "A calm one-hour yoga class for gentle movement, breath, and a grounded start to the day.",
  },
];

export function getEventBySlug(slug: string) {
  return events.find((event) => event.slug === slug);
}
